server:
  port: 8761
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  cloud:
    config:
      import-check:
        enabled: false
  application:
    name: service-discovery
