server:
  port: 9001
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service
  datasource:
    username: admin
    url: jdbc:postgresql://localhost:5435/user-service
    password: admin
    liquibase:
      enabled: true
      change-log: 'classpath:db/changelog/changelog-master.yaml'
      url: 'jdbc:postgresql://localhost:5435/user-service'
      user: 'admin'
      password: 'admin'
      parameters:
        user.id: '86d37949-2280-4eda-ae08-1cb86ec11a24'
        user.first-name: 'Dzmitry'
        user.last-name: 'Brouka'
        user.email: 'brovar2012@gmail.com'
        user.password: '$2y$10$L9KgE'
        user.role: 'ROLE_SUPER_ADMIN'
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.security: DEBUG